/**
 * v3.0 Self-Hosting Benchmark — Progmune generating Progmune
 *
 * 5 real features for Progmune, generated by Progmune.
 */

import { plan } from "./src/planner";
import { emitCode } from "./src/emitter";
import * as fs from "fs";

const TASKS = [
  {
    name: "benchmark_dashboard",
    intent: "load benchmarks and compute pass rate, then format a readable report with pass/fail counts",
    desc: "Benchmark result dashboard",
  },
  {
    name: "failure_trend",
    intent: "get failure genome and top failure patterns, then format as a trend report showing SVL distribution",
    desc: "Failure trend analysis report",
  },
  {
    name: "ledger_explorer",
    intent: "list all sessions and count their ledgers, checking ledger consistency for each and reporting violations",
    desc: "Ledger state explorer",
  },
  {
    name: "immune_monitor",
    intent: "compute immune metrics including antibody hits and token savings, then format as health status",
    desc: "Immune system health monitor",
  },
  {
    name: "capability_viewer",
    intent: "export all exported functions with their purpose requires and produces, formatted as a capability catalog",
    desc: "Capability graph viewer",
  },
];

async function main() {
  console.log("═══ v3.0 Self-Hosting Benchmark ═══\n");

  const results: { name: string; desc: string; success: boolean; actions: number; lines: number; retries: number }[] = [];

  for (const task of TASKS) {
    console.log(`── ${task.name}: ${task.desc} ──`);
    try {
      const start = Date.now();
      const result = await plan(task.intent);
      const elapsed = Date.now() - start;
      const actions = result.actions || [];
      const retries = (result.attempts?.length || 1) - 1;

      if (actions.length > 0 && actions.length < 50) {
        const code = emitCode(actions, {
          sessionId: result.sessionId,
          irFunctionCount: 549,
          protocolRuleCount: 7,
        });
        const file = `progmune-self/${task.name}.ts`;
        fs.writeFileSync(file, code);
        const lines = code.split("\n").length;
        console.log(`  ✅ ${actions.length} actions | ${lines} lines | ${elapsed}ms | ${retries} retries`);
        results.push({ name: task.name, desc: task.desc, success: true, actions: actions.length, lines, retries });
      } else {
        console.log(`  ❌ Invalid output (${actions.length} actions)`);
        results.push({ name: task.name, desc: task.desc, success: false, actions: actions.length, lines: 0, retries });
      }
    } catch (e: any) {
      console.log(`  💥 ${e.message?.slice(0, 50)}`);
      results.push({ name: task.name, desc: task.desc, success: false, actions: 0, lines: 0, retries: 99 });
    }
  }

  // Summary
  const success = results.filter(r => r.success);
  console.log(`\n═══════ Benchmark Results ═══════`);
  console.log(`  Generated:    ${success.length}/${TASKS.length}`);
  console.log(`  Avg actions:  ${(results.reduce((s, r) => s + r.actions, 0) / results.length).toFixed(1)}`);
  console.log(`  Avg lines:    ${(results.reduce((s, r) => s + r.lines, 0) / results.length).toFixed(0)}`);
  console.log(`  Avg retries:  ${(results.reduce((s, r) => s + r.retries, 0) / results.length).toFixed(1)}`);

  // Write benchmark report
  let report = "# Progmune Self-Hosting Benchmark\n\n";
  report += `Generated: ${new Date().toISOString()}\n\n`;
  report += "| Task | Description | Success | Actions | Lines | Retries |\n";
  report += "|------|------------|---------|---------|-------|--------|\n";
  for (const r of results) {
    report += `| ${r.name} | ${r.desc} | ${r.success ? "✅" : "❌"} | ${r.actions} | ${r.lines} | ${r.retries} |\n`;
  }
  report += `\n**Success Rate: ${success.length}/${TASKS.length}**\n`;
  fs.writeFileSync("progmune-self/BENCHMARK.md", report);
  console.log(`\n  Report: progmune-self/BENCHMARK.md`);
}

main().catch(console.error);
