/**
 * Progmune V3.4 — Protocol Mining Engine
 * ========================================
 * 从状态机恢复业务协议（Business Protocol）。
 *
 * 核心理念:
 *   State Machine 回答 "状态怎么变化"。
 *   Protocol 回答 "为什么必须这么走"——不是描述事实，而是陈述不变量。
 *
 * 协议 = 一组 Invariant（不变量）:
 *   ∀ Production ⇒ Paid=true          "生产必须先付款"
 *   ∀ Reward ⇒ LedgerExists           "奖励必须在账本写入后"
 *   ∀ Callback ⇒ SignatureValid       "回调签名必须有效"
 *   ∀ Callback ⇒ Idempotent           "回调不可重放"
 *
 * 输入: State Machines (V3.3) + Behavior Graph (V3.2)
 * 输出: Protocol — 一组可验证的 Invariant
 */

import * as path from "path";
import * as fs from "fs";

// ══════════════════════════════════════════════
// TYPES
// ══════════════════════════════════════════════

interface Invariant {
  id: string;                    // e.g. "INV-001"
  description: string;           // Human-readable: "生产必须先付款"
  predicate: string;             // Logical: "Production ⇒ Paid"
  domain: string;                // e.g. "Payment", "Order", "Auth"
  category: "prerequisite" | "safety" | "liveness" | "idempotency" | "integrity";
  severity: "critical" | "high" | "medium";
  sources: string[];             // Which state transitions / edges support this
  confidence: number;            // 0-100
  autoGenerated: boolean;
}

interface BusinessProtocol {
  name: string;                  // e.g. "Payment Protocol"
  domain: string;                // e.g. "payment"
  description: string;
  invariants: Invariant[];
  stateMachine: string;          // Which state machine this protocol refines
  confidence: number;
}

// ══════════════════════════════════════════════
// INVARIANT PATTERNS (business rules derived from state machines)
// ══════════════════════════════════════════════

/**
 * Given a state machine with transitions A→B→C,
 * derive invariants of the form: "B requires A", "C requires B", etc.
 * Also derive: "A must be unique", "C must be idempotent", etc.
 */
function deriveFromStateMachine(machine: any): Invariant[] {
  const invariants: Invariant[] = [];
  const states = machine.states || [];
  const transitions = machine.transitions || [];
  const entity = machine.entity || "unknown";
  let nextId = 1;

  // ── Pattern 1: State ordering prerequisites ──
  // For each transition A→B, derive: "B requires A"
  // BUT: if BOTH A→B and B→A exist, neither is a prerequisite — they're bidirectional.
  // A cycle in REQUIRES is a logical contradiction; bidirectional edges cancel out.

  // Build set of valid transition pairs for bidirectional check
  const validPairs = new Set<string>();
  for (const t of transitions) {
    if (t.from !== "INITIAL" && t.from !== "UNKNOWN") {
      validPairs.add(`${t.from}→${t.to}`);
    }
  }

  for (const t of transitions) {
    if (t.from === "INITIAL" || t.from === "UNKNOWN") continue;

    // Check: does the reverse transition also exist? If so, it's bidirectional → skip
    const reverse = `${t.to}→${t.from}`;
    if (validPairs.has(reverse)) {
      // Both directions exist — this is not a strict prerequisite
      continue;
    }

    invariants.push({
      id: `INV-${nextId++}`,
      description: `${t.to} 状态必须先经过 ${t.from} 状态`,
      predicate: `${t.to} ⇒ ${t.from}`,
      domain: entity,
      category: "prerequisite",
      severity: "critical",
      sources: [`State transition: ${t.from}→${t.to}`],
      confidence: t.confidence || 40,
      autoGenerated: true,
    });
  }

  // ── Pattern 2: Terminal states are irreversible ──
  const terminalStates = machine.terminalStates || [];
  for (const ts of terminalStates) {
    invariants.push({
      id: `INV-${nextId++}`,
      description: `${ts} 是终态——一旦进入不可回退`,
      predicate: `${ts} ⇒ ¬∃ next_state`,
      domain: entity,
      category: "integrity",
      severity: "high",
      sources: [`Terminal state: ${ts}`],
      confidence: 70,
      autoGenerated: true,
    });
  }

  // ── Pattern 3: Invalid transitions are violations ──
  const invalidTransitions = machine.invalidTransitions || [];
  for (const inv of invalidTransitions.slice(0, 10)) {
    const [from, to] = inv.split("→");
    if (!from || !to) continue;
    invariants.push({
      id: `INV-${nextId++}`,
      description: `禁止从 ${from} 直接跳转到 ${to}——中间状态缺失`,
      predicate: `¬(${from} → ${to})`,
      domain: entity,
      category: "safety",
      severity: "high",
      sources: [`Invalid transition: ${inv}`],
      confidence: 80,
      autoGenerated: true,
    });
  }

  // ── Pattern 4: Initial state is unique ──
  const initialState = machine.initialState;
  if (initialState && initialState !== "UNKNOWN") {
    invariants.push({
      id: `INV-${nextId++}`,
      description: `${initialState} 是唯一合法起始状态`,
      predicate: `∀ entity ∈ ${entity}: initial_state(entity) = ${initialState}`,
      domain: entity,
      category: "integrity",
      severity: "medium",
      sources: [`Initial state: ${initialState}`],
      confidence: 90,
      autoGenerated: true,
    });
  }

  return invariants;
}

// ══════════════════════════════════════════════
// DOMAIN-SPECIFIC INVARIANT TEMPLATES
// ══════════════════════════════════════════════

/**
 * Business domain knowledge: known invariants for common domains.
 * These are templates — the miner matches state names to these templates
 * and instantiates the invariants with actual state values.
 */
const DOMAIN_INVARIANTS: Record<string, Invariant[]> = {
  "orders": [
    { id:"TMPL-001", description:"必须先付款才能进入生产", predicate:"Production ⇒ Paid", domain:"orders", category:"prerequisite", severity:"critical", sources:["Domain:order_lifecycle"], confidence:95, autoGenerated:true },
    { id:"TMPL-002", description:"必须先完成生产才能发货", predicate:"Shipped ⇒ Production", domain:"orders", category:"prerequisite", severity:"critical", sources:["Domain:order_lifecycle"], confidence:95, autoGenerated:true },
    { id:"TMPL-003", description:"已取消的订单不可恢复", predicate:"Cancelled ⇒ ¬∃ next_state", domain:"orders", category:"integrity", severity:"high", sources:["Domain:order_lifecycle"], confidence:90, autoGenerated:true },
    { id:"TMPL-004", description:"每个订单有且仅有一次支付", predicate:"∀ order: |payments(order)| ≤ 1", domain:"orders", category:"idempotency", severity:"high", sources:["Domain:payment"], confidence:85, autoGenerated:true },
  ],
  "payment": [
    { id:"TMPL-005", description:"支付回调签名必须验证", predicate:"Callback ⇒ SignatureValid", domain:"payment", category:"safety", severity:"critical", sources:["Domain:payment_callback"], confidence:98, autoGenerated:true },
    { id:"TMPL-006", description:"支付回调不可重放", predicate:"Callback ⇒ Idempotent", domain:"payment", category:"idempotency", severity:"critical", sources:["Domain:payment_callback"], confidence:98, autoGenerated:true },
    { id:"TMPL-007", description:"退款只能在支付确认后", predicate:"Refund ⇒ Confirmed", domain:"payment", category:"prerequisite", severity:"critical", sources:["Domain:payment_refund"], confidence:95, autoGenerated:true },
    { id:"TMPL-008", description:"支付必须有对应订单", predicate:"Payment ⇒ ∃ Order", domain:"payment", category:"integrity", severity:"critical", sources:["Domain:payment_order"], confidence:98, autoGenerated:true },
  ],
  "auth": [
    { id:"TMPL-009", description:"每次资源访问必须认证", predicate:"Access ⇒ Authenticated", domain:"auth", category:"safety", severity:"critical", sources:["Domain:auth"], confidence:99, autoGenerated:true },
    { id:"TMPL-010", description:"密码必须哈希存储", predicate:"Store ⇒ Hashed", domain:"auth", category:"safety", severity:"critical", sources:["Domain:password"], confidence:99, autoGenerated:true },
    { id:"TMPL-011", description:"会话超时后自动失效", predicate:"Timeout ⇒ SessionInvalid", domain:"auth", category:"liveness", severity:"high", sources:["Domain:session"], confidence:90, autoGenerated:true },
  ],
  "file_upload": [
    { id:"TMPL-012", description:"上传文件必须验证类型", predicate:"Store ⇒ Validated", domain:"file_upload", category:"safety", severity:"high", sources:["Domain:file_upload"], confidence:90, autoGenerated:true },
    { id:"TMPL-013", description:"文件大小必须限制", predicate:"Upload ⇒ SizeWithinLimit", domain:"file_upload", category:"safety", severity:"medium", sources:["Domain:file_upload"], confidence:85, autoGenerated:true },
  ],
};

/**
 * Match discovered state names to domain templates.
 * e.g. if we found states ["pending_payment","paid","production","shipped"],
 * match against the "orders" domain templates.
 */
function matchDomainTemplates(
  states: string[],
  entityName: string
): Invariant[] {
  const matched: Invariant[] = [];
  const entityLower = entityName.toLowerCase();
  const statesLower = states.map(s => s.toLowerCase());

  // Match entity name to domain
  let domainKey: string | null = null;
  if (entityLower.includes("order")) domainKey = "orders";
  else if (entityLower.includes("payment") || entityLower.includes("pay")) domainKey = "payment";
  else if (entityLower.includes("auth") || entityLower.includes("user") || entityLower.includes("login")) domainKey = "auth";
  else if (entityLower.includes("upload") || entityLower.includes("file")) domainKey = "file_upload";

  if (!domainKey) return matched;

  const templates = DOMAIN_INVARIANTS[domainKey] || [];

  for (const tpl of templates) {
    // Instantiate the template with actual state names
    let predicate = tpl.predicate;
    let description = tpl.description;

    // Replace template variables with actual state names
    // e.g. "Production ⇒ Paid" → "production ⇒ paid"
    for (const s of states) {
      const sLower = s.toLowerCase();
      // Check if this state matches a template variable
      if (sLower.includes("production") || sLower.includes("manufacturing")) {
        predicate = predicate.replace(/Production/g, s);
      }
      if (sLower.includes("paid") || sLower.includes("confirmed_payment")) {
        predicate = predicate.replace(/Paid/g, s);
      }
      if (sLower.includes("shipped") || sLower.includes("delivered") || sLower.includes("completed")) {
        predicate = predicate.replace(/Shipped/g, s);
        predicate = predicate.replace(/Completed/g, s);
      }
      if (sLower.includes("cancelled") || sLower.includes("canceled")) {
        predicate = predicate.replace(/Cancelled/g, s);
      }
    }

    matched.push({
      ...tpl,
      id: `INV-${tpl.id}`,
      predicate,
      description,
      confidence: tpl.confidence - 10, // Slightly lower: template match is less confident than code-derived
      sources: [...tpl.sources, `Matched from state: ${entityName} [${states.join(",")}]`],
    });
  }

  return matched;
}

// ══════════════════════════════════════════════
// L4: PROTOCOL ASSEMBLY
// ══════════════════════════════════════════════

/**
 * From state machines, assemble business protocols.
 * A protocol = state-machine-derived invariants + domain-template invariants.
 */
function assembleProtocols(machines: any[]): BusinessProtocol[] {
  const protocols: BusinessProtocol[] = [];

  for (const machine of machines) {
    const states = machine.states || [];
    if (states.length < 2) continue;

    // Derive invariants from the state machine structure
    const derivedInvariants = deriveFromStateMachine(machine);

    // Match domain templates
    const templateInvariants = matchDomainTemplates(states, machine.entity);

    // Combine (deduplicate by predicate)
    const allInvariants = [...derivedInvariants];
    for (const tpl of templateInvariants) {
      if (!allInvariants.find(i => i.predicate === tpl.predicate)) {
        allInvariants.push(tpl);
      }
    }

    // Compute overall confidence
    const avgConf = Math.round(
      allInvariants.reduce((s, i) => s + i.confidence, 0) / Math.max(1, allInvariants.length)
    );

    protocols.push({
      name: `${machine.entity} Protocol`,
      domain: machine.entity,
      description: `${allInvariants.length} invariants governing ${machine.entity} lifecycle`,
      invariants: allInvariants,
      stateMachine: machine.entity,
      confidence: avgConf,
    });
  }

  return protocols;
}

// ══════════════════════════════════════════════
// MAIN PIPELINE
// ══════════════════════════════════════════════

interface ProtocolMiningReport {
  projectPath: string;
  timestamp: string;
  protocols: BusinessProtocol[];
  summary: {
    protocolsFound: number;
    totalInvariants: number;
    criticalInvariants: number;
    highConfidenceProtocols: number;
  };
}

export function mineProtocols(projectPath: string): ProtocolMiningReport {
  console.log("🔬 Progmune Protocol Mining Engine — V3.4");
  console.log("   Project:", projectPath);

  // Load state machines from V3.3 output
  const stateMachinesPath = path.join(projectPath, ".progmune_state_machines.json");
  let machines: any[] = [];

  if (fs.existsSync(stateMachinesPath)) {
    const data = JSON.parse(fs.readFileSync(stateMachinesPath, "utf-8"));
    machines = data.machines || [];
    console.log(`   Loaded ${machines.length} state machines from V3.3`);
  } else {
    console.log("   No state machines found. Run V3.3 first: npx ts-node src/state-miner.ts");
    return {
      projectPath, timestamp: new Date().toISOString(), protocols: [],
      summary: { protocolsFound: 0, totalInvariants: 0, criticalInvariants: 0, highConfidenceProtocols: 0 },
    };
  }

  // L4: Protocol Assembly
  console.log("\nL4 · Protocol Assembly...");
  const protocols = assembleProtocols(machines);
  console.log(`   ${protocols.length} protocols assembled`);

  for (const proto of protocols) {
    const criticalCount = proto.invariants.filter(i => i.severity === "critical").length;
    console.log(`\n   📜 ${proto.name} [${proto.confidence}%]`);
    console.log(`      ${proto.description}`);
    console.log(`      ${proto.invariants.length} invariants (${criticalCount} critical):`);
    for (const inv of proto.invariants) {
      const sevIcon = inv.severity === "critical" ? "🔴" : inv.severity === "high" ? "🟠" : "🟡";
      console.log(`        ${sevIcon} ${inv.id}: ${inv.description}`);
      console.log(`           ${inv.predicate} [${inv.confidence}%] [${inv.category}]`);
    }
  }

  // Summary
  const allInvariants = protocols.flatMap(p => p.invariants);
  const report: ProtocolMiningReport = {
    projectPath,
    timestamp: new Date().toISOString(),
    protocols,
    summary: {
      protocolsFound: protocols.length,
      totalInvariants: allInvariants.length,
      criticalInvariants: allInvariants.filter(i => i.severity === "critical").length,
      highConfidenceProtocols: protocols.filter(p => p.confidence >= 60).length,
    },
  };

  return report;
}

// ══════════════════════════════════════════════
// CLI
// ══════════════════════════════════════════════

if (require.main === module) {
  const targetProject = process.argv[2];
  if (!targetProject) {
    console.error("Usage: npx ts-node src/protocol-miner.ts <project-path>");
    process.exit(1);
  }

  const report = mineProtocols(targetProject);

  const outputPath = path.join(targetProject, ".progmune_protocols.json");
  fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
  console.log(`\n✅ Protocols saved to: ${outputPath}`);

  console.log("\n═══ Protocol Mining Summary ═══");
  console.log(`  Protocols:  ${report.summary.protocolsFound}`);
  console.log(`  Invariants: ${report.summary.totalInvariants} (${report.summary.criticalInvariants} critical)`);
  console.log(`  High conf:  ${report.summary.highConfidenceProtocols}`);
  console.log();
}
