// @progmune-generated session=sess_1780302758601_if0oc timestamp=2026-06-01T08:32:43.200Z ruleHash=9dec68bc2995e92a
// Generated with IR constraint: 415 functions, 17 protocol rules
import { getBranchPath } from "./branch-ledger";
import { getImportPath } from "./emitter";
import { getExecutionMetrics } from "./execute";
import { getTypeDetail, getParamType, getParamTypeDetail, getReturnType, getReturnTypeDetail, extractDirectCalls } from "./extract-ir";
import { getAllFailures, getFailuresBySVL, getTopFailurePatterns, getFailureGenome, getAllSessions, getLearnedPatterns, getSemanticHeatmap, getAntibodyStats, generateCandidateRules } from "./failure-corpus";
import { getFunctionSuccessRate } from "./feedback";
import { getInstanceId, getReportCursor } from "./immune-reporter";
import { getFingerprint, getFingerprintRegistry, verifyAllFingerprints, registerAllMissingFingerprints } from "./ledger-registry";
import { getRecentEpisodes, getSuccessfulEpisodes, WorkMemory.getIntent, WorkMemory.get } from "./memory-layer";
import { getSessionTransitions, handleAPI, handleLedgerAPI, handleConsistencyAPI, handleDiffAPI, handleReplayAPI } from "./obs-web";
import { getProtocolConfig, getNsInit, getRuleHash } from "./protocol-registry";
import { getMinimalFixSet } from "./repair-proposal";
import { getStaticScore } from "./search-planner";
import { StateMachineValidator.getCurrentStates, StateMachineValidator.getNamespaceStates, StateMachineValidator.getTrace, StateMachineValidator.getLedger, StateMachineValidator.getContext, StateMachineValidator.getRuleHash, listAllStates } from "./ssg-validator";
import { ActionBuilder.call } from "./action-runtime";
import { resetCallCount } from "./llm";
import { generateFallbackPlan, attemptSSGRepair } from "./planner";
import { formatSessionSummary, formatHeatmap } from "./semantic-trace";
import { scanDir } from "./audit";
import { runAndCheck } from "./runtime";
import { findSnapshotBySession } from "./semantic-snapshot";
import type { Branch, Map } from "./branch-ledger";
import type { FunctionDeclaration } from "./extract-ir";
import type { SVL } from "./failure-corpus";
import type { RepairProposal } from "./repair-proposal";
import type { StateTransition } from "./ssg-validator";
import type { AuditResult } from "./audit";
import type { URL } from "./obs-web";
import type { Action, SSGRejection, FunctionProtocol, Map } from "./planner";

export function main() {
  const getBranchPath_result = getBranchPath({} as Branch, {} as Map<string, Branch>);
  const getImportPath_result = getImportPath("defaultStr");
  const getExecutionMetrics_result = getExecutionMetrics();
  const getTypeDetail_result = getTypeDetail("default");
  const getParamType_result = getParamType("default");
  const getParamTypeDetail_result = getParamTypeDetail("default");
  const getReturnType_result = getReturnType({} as FunctionDeclaration | ArrowFunction);
  const getReturnTypeDetail_result = getReturnTypeDetail({} as FunctionDeclaration | ArrowFunction);
  const getAllFailures_result = getAllFailures();
  const getFailuresBySVL_result = getFailuresBySVL({} as SVL);
  const getTopFailurePatterns_result = getTopFailurePatterns(0);
  const getFailureGenome_result = getFailureGenome();
  const getAllSessions_result = getAllSessions();
  const getLearnedPatterns_result = getLearnedPatterns();
  const getSemanticHeatmap_result = getSemanticHeatmap();
  const getAntibodyStats_result = getAntibodyStats();
  const getFunctionSuccessRate_result = getFunctionSuccessRate("defaultStr");
  const getInstanceId_result = getInstanceId();
  const getReportCursor_result = getReportCursor();
  const getFingerprint_result = getFingerprint("defaultStr");
  const getFingerprintRegistry_result = getFingerprintRegistry();
  const getRecentEpisodes_result = getRecentEpisodes(0);
  const getSuccessfulEpisodes_result = getSuccessfulEpisodes(0);
  const WorkMemory.getIntent_result = WorkMemory.getIntent();
  const WorkMemory.get_result = WorkMemory.get("defaultStr");
  const getSessionTransitions_result = getSessionTransitions("default");
  const getProtocolConfig_result = getProtocolConfig();
  const getNsInit_result = getNsInit();
  const getRuleHash_result = getRuleHash();
  const getMinimalFixSet_result = getMinimalFixSet({} as RepairProposal[]);
  const getStaticScore_result = getStaticScore("defaultStr", "defaultStr");
  const StateMachineValidator.getCurrentStates_result = StateMachineValidator.getCurrentStates();
  const StateMachineValidator.getNamespaceStates_result = StateMachineValidator.getNamespaceStates("defaultStr");
  const StateMachineValidator.getTrace_result = StateMachineValidator.getTrace();
  const StateMachineValidator.getLedger_result = StateMachineValidator.getLedger();
  const StateMachineValidator.getContext_result = StateMachineValidator.getContext();
  const StateMachineValidator.getRuleHash_result = StateMachineValidator.getRuleHash();
  const getElementTypeNode_result = getElementTypeNode();
  const getTypeNode_result = getTypeNode();
  const getReturnTypeNode_result = getReturnTypeNode();
  const getBody_result = getBody();
  const getClasses_result = getClasses();
  const getMethods_result = getMethods();
  const getImportDeclarations_result = getImportDeclarations();
  const getModuleSpecifierValue_result = getModuleSpecifierValue();
  const getNamedImports_result = getNamedImports();
  const getModuleSpecifierSourceFile_result = getModuleSpecifierSourceFile();
  const getNamespaceImport_result = getNamespaceImport();
  const getExportedDeclarations_result = getExportedDeclarations();
  const getTrace_result = getTrace();
  const getMaskedFuncList_result = getMaskedFuncList();
  const ActionBuilder.call_result = ActionBuilder.call("defaultStr", {} as any[], "defaultStr");
  const extractDirectCalls_result = extractDirectCalls({} as FunctionDeclaration | ArrowFunction);
  const verifyAllFingerprints_result = verifyAllFingerprints("defaultStr");
  const registerAllMissingFingerprints_result = registerAllMissingFingerprints();
  const resetCallCount_result = resetCallCount();
  const generateFallbackPlan_result = generateFallbackPlan("defaultStr", {} as any[]);
  const listAllStates_result = listAllStates({} as StateTransition[]);
  const formatSessionSummary_result = formatSessionSummary({} as ReturnType<typeof getAllSessions>);
  const result_0 = scanDir("defaultStr", "defaultStr", {} as AuditResult);
  const generateCandidateRules_result = generateCandidateRules();
  const handleAPI_result = handleAPI({} as http.IncomingMessage, {} as http.ServerResponse);
  const handleLedgerAPI_result = handleLedgerAPI({} as http.ServerResponse, {} as URL);
  const handleConsistencyAPI_result = handleConsistencyAPI({} as http.ServerResponse, {} as URL);
  const handleDiffAPI_result = handleDiffAPI({} as http.ServerResponse, {} as URL);
  const handleReplayAPI_result = handleReplayAPI({} as http.ServerResponse, {} as URL);
  const runAndCheck_result = runAndCheck("defaultStr");
  const random_result = random();
  const handler_result = handler();
  const findSnapshotBySession_result = findSnapshotBySession("defaultStr");
  const formatHeatmap_result = formatHeatmap();
  const toFixed_result = toFixed();
  const attemptSSGRepair_result = attemptSSGRepair({} as Action[], {} as SSGRejection, {} as any[], {} as FunctionProtocol[], {} as Map<string, string>);
}
main();
